# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 08:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Errand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='Blank Title', max_length=100)),
                ('text', models.TextField()),
                ('extraCost', models.PositiveIntegerField()),
                ('reward', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('DELIVERY', 'Delivery'), ('HOMEWORK', 'Homework'), ('ERRAND', 'Errand'), ('ETC', 'Etc')], default='DELIVERY', max_length=10)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='errand', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
